// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment_service.proto

package com.londonsmartcity.environment;

/**
 * Protobuf type {@code com.londonsmartcity.environment.AirQualityResponse}
 */
public final class AirQualityResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.londonsmartcity.environment.AirQualityResponse)
    AirQualityResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AirQualityResponse.newBuilder() to construct.
  private AirQualityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AirQualityResponse() {
    locationId_ = "";
    airQualityIndex_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AirQualityResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AirQualityResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            locationId_ = s;
            break;
          }
          case 17: {

            pm25_ = input.readDouble();
            break;
          }
          case 25: {

            pm10_ = input.readDouble();
            break;
          }
          case 33: {

            no2_ = input.readDouble();
            break;
          }
          case 41: {

            o3_ = input.readDouble();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            airQualityIndex_ = s;
            break;
          }
          case 56: {

            timestamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.londonsmartcity.environment.EnvironmentServiceProto.internal_static_com_londonsmartcity_environment_AirQualityResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.londonsmartcity.environment.EnvironmentServiceProto.internal_static_com_londonsmartcity_environment_AirQualityResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.londonsmartcity.environment.AirQualityResponse.class, com.londonsmartcity.environment.AirQualityResponse.Builder.class);
  }

  public static final int LOCATION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object locationId_;
  /**
   * <code>string location_id = 1;</code>
   * @return The locationId.
   */
  @java.lang.Override
  public java.lang.String getLocationId() {
    java.lang.Object ref = locationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      locationId_ = s;
      return s;
    }
  }
  /**
   * <code>string location_id = 1;</code>
   * @return The bytes for locationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocationIdBytes() {
    java.lang.Object ref = locationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      locationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PM25_FIELD_NUMBER = 2;
  private double pm25_;
  /**
   * <code>double pm25 = 2;</code>
   * @return The pm25.
   */
  @java.lang.Override
  public double getPm25() {
    return pm25_;
  }

  public static final int PM10_FIELD_NUMBER = 3;
  private double pm10_;
  /**
   * <code>double pm10 = 3;</code>
   * @return The pm10.
   */
  @java.lang.Override
  public double getPm10() {
    return pm10_;
  }

  public static final int NO2_FIELD_NUMBER = 4;
  private double no2_;
  /**
   * <code>double no2 = 4;</code>
   * @return The no2.
   */
  @java.lang.Override
  public double getNo2() {
    return no2_;
  }

  public static final int O3_FIELD_NUMBER = 5;
  private double o3_;
  /**
   * <code>double o3 = 5;</code>
   * @return The o3.
   */
  @java.lang.Override
  public double getO3() {
    return o3_;
  }

  public static final int AIR_QUALITY_INDEX_FIELD_NUMBER = 6;
  private volatile java.lang.Object airQualityIndex_;
  /**
   * <code>string air_quality_index = 6;</code>
   * @return The airQualityIndex.
   */
  @java.lang.Override
  public java.lang.String getAirQualityIndex() {
    java.lang.Object ref = airQualityIndex_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      airQualityIndex_ = s;
      return s;
    }
  }
  /**
   * <code>string air_quality_index = 6;</code>
   * @return The bytes for airQualityIndex.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAirQualityIndexBytes() {
    java.lang.Object ref = airQualityIndex_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      airQualityIndex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, locationId_);
    }
    if (java.lang.Double.doubleToRawLongBits(pm25_) != 0) {
      output.writeDouble(2, pm25_);
    }
    if (java.lang.Double.doubleToRawLongBits(pm10_) != 0) {
      output.writeDouble(3, pm10_);
    }
    if (java.lang.Double.doubleToRawLongBits(no2_) != 0) {
      output.writeDouble(4, no2_);
    }
    if (java.lang.Double.doubleToRawLongBits(o3_) != 0) {
      output.writeDouble(5, o3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(airQualityIndex_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, airQualityIndex_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, locationId_);
    }
    if (java.lang.Double.doubleToRawLongBits(pm25_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, pm25_);
    }
    if (java.lang.Double.doubleToRawLongBits(pm10_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, pm10_);
    }
    if (java.lang.Double.doubleToRawLongBits(no2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, no2_);
    }
    if (java.lang.Double.doubleToRawLongBits(o3_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, o3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(airQualityIndex_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, airQualityIndex_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.londonsmartcity.environment.AirQualityResponse)) {
      return super.equals(obj);
    }
    com.londonsmartcity.environment.AirQualityResponse other = (com.londonsmartcity.environment.AirQualityResponse) obj;

    if (!getLocationId()
        .equals(other.getLocationId())) return false;
    if (java.lang.Double.doubleToLongBits(getPm25())
        != java.lang.Double.doubleToLongBits(
            other.getPm25())) return false;
    if (java.lang.Double.doubleToLongBits(getPm10())
        != java.lang.Double.doubleToLongBits(
            other.getPm10())) return false;
    if (java.lang.Double.doubleToLongBits(getNo2())
        != java.lang.Double.doubleToLongBits(
            other.getNo2())) return false;
    if (java.lang.Double.doubleToLongBits(getO3())
        != java.lang.Double.doubleToLongBits(
            other.getO3())) return false;
    if (!getAirQualityIndex()
        .equals(other.getAirQualityIndex())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLocationId().hashCode();
    hash = (37 * hash) + PM25_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPm25()));
    hash = (37 * hash) + PM10_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPm10()));
    hash = (37 * hash) + NO2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNo2()));
    hash = (37 * hash) + O3_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getO3()));
    hash = (37 * hash) + AIR_QUALITY_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getAirQualityIndex().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.londonsmartcity.environment.AirQualityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.londonsmartcity.environment.AirQualityResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.londonsmartcity.environment.AirQualityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.londonsmartcity.environment.AirQualityResponse)
      com.londonsmartcity.environment.AirQualityResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.londonsmartcity.environment.EnvironmentServiceProto.internal_static_com_londonsmartcity_environment_AirQualityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.londonsmartcity.environment.EnvironmentServiceProto.internal_static_com_londonsmartcity_environment_AirQualityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.londonsmartcity.environment.AirQualityResponse.class, com.londonsmartcity.environment.AirQualityResponse.Builder.class);
    }

    // Construct using com.londonsmartcity.environment.AirQualityResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      locationId_ = "";

      pm25_ = 0D;

      pm10_ = 0D;

      no2_ = 0D;

      o3_ = 0D;

      airQualityIndex_ = "";

      timestamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.londonsmartcity.environment.EnvironmentServiceProto.internal_static_com_londonsmartcity_environment_AirQualityResponse_descriptor;
    }

    @java.lang.Override
    public com.londonsmartcity.environment.AirQualityResponse getDefaultInstanceForType() {
      return com.londonsmartcity.environment.AirQualityResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.londonsmartcity.environment.AirQualityResponse build() {
      com.londonsmartcity.environment.AirQualityResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.londonsmartcity.environment.AirQualityResponse buildPartial() {
      com.londonsmartcity.environment.AirQualityResponse result = new com.londonsmartcity.environment.AirQualityResponse(this);
      result.locationId_ = locationId_;
      result.pm25_ = pm25_;
      result.pm10_ = pm10_;
      result.no2_ = no2_;
      result.o3_ = o3_;
      result.airQualityIndex_ = airQualityIndex_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.londonsmartcity.environment.AirQualityResponse) {
        return mergeFrom((com.londonsmartcity.environment.AirQualityResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.londonsmartcity.environment.AirQualityResponse other) {
      if (other == com.londonsmartcity.environment.AirQualityResponse.getDefaultInstance()) return this;
      if (!other.getLocationId().isEmpty()) {
        locationId_ = other.locationId_;
        onChanged();
      }
      if (other.getPm25() != 0D) {
        setPm25(other.getPm25());
      }
      if (other.getPm10() != 0D) {
        setPm10(other.getPm10());
      }
      if (other.getNo2() != 0D) {
        setNo2(other.getNo2());
      }
      if (other.getO3() != 0D) {
        setO3(other.getO3());
      }
      if (!other.getAirQualityIndex().isEmpty()) {
        airQualityIndex_ = other.airQualityIndex_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.londonsmartcity.environment.AirQualityResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.londonsmartcity.environment.AirQualityResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object locationId_ = "";
    /**
     * <code>string location_id = 1;</code>
     * @return The locationId.
     */
    public java.lang.String getLocationId() {
      java.lang.Object ref = locationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location_id = 1;</code>
     * @return The bytes for locationId.
     */
    public com.google.protobuf.ByteString
        getLocationIdBytes() {
      java.lang.Object ref = locationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location_id = 1;</code>
     * @param value The locationId to set.
     * @return This builder for chaining.
     */
    public Builder setLocationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      locationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string location_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocationId() {
      
      locationId_ = getDefaultInstance().getLocationId();
      onChanged();
      return this;
    }
    /**
     * <code>string location_id = 1;</code>
     * @param value The bytes for locationId to set.
     * @return This builder for chaining.
     */
    public Builder setLocationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      locationId_ = value;
      onChanged();
      return this;
    }

    private double pm25_ ;
    /**
     * <code>double pm25 = 2;</code>
     * @return The pm25.
     */
    @java.lang.Override
    public double getPm25() {
      return pm25_;
    }
    /**
     * <code>double pm25 = 2;</code>
     * @param value The pm25 to set.
     * @return This builder for chaining.
     */
    public Builder setPm25(double value) {
      
      pm25_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double pm25 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPm25() {
      
      pm25_ = 0D;
      onChanged();
      return this;
    }

    private double pm10_ ;
    /**
     * <code>double pm10 = 3;</code>
     * @return The pm10.
     */
    @java.lang.Override
    public double getPm10() {
      return pm10_;
    }
    /**
     * <code>double pm10 = 3;</code>
     * @param value The pm10 to set.
     * @return This builder for chaining.
     */
    public Builder setPm10(double value) {
      
      pm10_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double pm10 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPm10() {
      
      pm10_ = 0D;
      onChanged();
      return this;
    }

    private double no2_ ;
    /**
     * <code>double no2 = 4;</code>
     * @return The no2.
     */
    @java.lang.Override
    public double getNo2() {
      return no2_;
    }
    /**
     * <code>double no2 = 4;</code>
     * @param value The no2 to set.
     * @return This builder for chaining.
     */
    public Builder setNo2(double value) {
      
      no2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double no2 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNo2() {
      
      no2_ = 0D;
      onChanged();
      return this;
    }

    private double o3_ ;
    /**
     * <code>double o3 = 5;</code>
     * @return The o3.
     */
    @java.lang.Override
    public double getO3() {
      return o3_;
    }
    /**
     * <code>double o3 = 5;</code>
     * @param value The o3 to set.
     * @return This builder for chaining.
     */
    public Builder setO3(double value) {
      
      o3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double o3 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearO3() {
      
      o3_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object airQualityIndex_ = "";
    /**
     * <code>string air_quality_index = 6;</code>
     * @return The airQualityIndex.
     */
    public java.lang.String getAirQualityIndex() {
      java.lang.Object ref = airQualityIndex_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        airQualityIndex_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string air_quality_index = 6;</code>
     * @return The bytes for airQualityIndex.
     */
    public com.google.protobuf.ByteString
        getAirQualityIndexBytes() {
      java.lang.Object ref = airQualityIndex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        airQualityIndex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string air_quality_index = 6;</code>
     * @param value The airQualityIndex to set.
     * @return This builder for chaining.
     */
    public Builder setAirQualityIndex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      airQualityIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string air_quality_index = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAirQualityIndex() {
      
      airQualityIndex_ = getDefaultInstance().getAirQualityIndex();
      onChanged();
      return this;
    }
    /**
     * <code>string air_quality_index = 6;</code>
     * @param value The bytes for airQualityIndex to set.
     * @return This builder for chaining.
     */
    public Builder setAirQualityIndexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      airQualityIndex_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.londonsmartcity.environment.AirQualityResponse)
  }

  // @@protoc_insertion_point(class_scope:com.londonsmartcity.environment.AirQualityResponse)
  private static final com.londonsmartcity.environment.AirQualityResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.londonsmartcity.environment.AirQualityResponse();
  }

  public static com.londonsmartcity.environment.AirQualityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AirQualityResponse>
      PARSER = new com.google.protobuf.AbstractParser<AirQualityResponse>() {
    @java.lang.Override
    public AirQualityResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AirQualityResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AirQualityResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AirQualityResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.londonsmartcity.environment.AirQualityResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

