// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment_service.proto

package com.londonsmartcity.environment;

public interface HistoricalDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.londonsmartcity.environment.HistoricalDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location_id = 1;</code>
   * @return The locationId.
   */
  java.lang.String getLocationId();
  /**
   * <code>string location_id = 1;</code>
   * @return The bytes for locationId.
   */
  com.google.protobuf.ByteString
      getLocationIdBytes();

  /**
   * <code>int64 start_time = 2;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 3;</code>
   * @return The endTime.
   */
  long getEndTime();
}
