// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment_service.proto

package com.londonsmartcity.environment;

public interface AirQualityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.londonsmartcity.environment.AirQualityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location_id = 1;</code>
   * @return The locationId.
   */
  java.lang.String getLocationId();
  /**
   * <code>string location_id = 1;</code>
   * @return The bytes for locationId.
   */
  com.google.protobuf.ByteString
      getLocationIdBytes();

  /**
   * <code>double pm25 = 2;</code>
   * @return The pm25.
   */
  double getPm25();

  /**
   * <code>double pm10 = 3;</code>
   * @return The pm10.
   */
  double getPm10();

  /**
   * <code>double no2 = 4;</code>
   * @return The no2.
   */
  double getNo2();

  /**
   * <code>double o3 = 5;</code>
   * @return The o3.
   */
  double getO3();

  /**
   * <code>string air_quality_index = 6;</code>
   * @return The airQualityIndex.
   */
  java.lang.String getAirQualityIndex();
  /**
   * <code>string air_quality_index = 6;</code>
   * @return The bytes for airQualityIndex.
   */
  com.google.protobuf.ByteString
      getAirQualityIndexBytes();

  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
