// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment_service.proto

package com.londonsmartcity.environment;

public interface AirQualityAlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.londonsmartcity.environment.AirQualityAlert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location_id = 1;</code>
   * @return The locationId.
   */
  java.lang.String getLocationId();
  /**
   * <code>string location_id = 1;</code>
   * @return The bytes for locationId.
   */
  com.google.protobuf.ByteString
      getLocationIdBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string severity = 3;</code>
   * @return The severity.
   */
  java.lang.String getSeverity();
  /**
   * <code>string severity = 3;</code>
   * @return The bytes for severity.
   */
  com.google.protobuf.ByteString
      getSeverityBytes();
}
