// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment_service.proto

package com.londonsmartcity.environment;

public final class EnvironmentServiceProto {
  private EnvironmentServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_EnvironmentalDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_EnvironmentalDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_EnvironmentalDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_EnvironmentalDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_AirQualityAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_AirQualityAlert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_AlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_AlertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_HistoricalDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_HistoricalDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_HistoricalDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_HistoricalDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_DataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_DataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_EnvironmentalUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_EnvironmentalUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environment_EnvironmentalUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environment_EnvironmentalUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031environment_service.proto\022\013environment" +
      "\"T\n\030EnvironmentalDataRequest\022\023\n\013location" +
      "_id\030\001 \001(\t\022\020\n\010latitude\030\002 \001(\001\022\021\n\tlongitude" +
      "\030\003 \001(\001\"\255\001\n\031EnvironmentalDataResponse\022\023\n\013" +
      "location_id\030\001 \001(\t\022\023\n\013temperature\030\002 \001(\001\022\020" +
      "\n\010humidity\030\003 \001(\001\022\031\n\021air_quality_index\030\004 " +
      "\001(\001\022\023\n\013noise_level\030\005 \001(\001\022\021\n\tco2_level\030\006 " +
      "\001(\001\022\021\n\ttimestamp\030\007 \001(\t\"\206\001\n\017AirQualityAle" +
      "rt\022\023\n\013location_id\030\001 \001(\t\022\022\n\nalert_type\030\002 " +
      "\001(\t\022\020\n\010severity\030\003 \001(\t\022\023\n\013description\030\004 \001" +
      "(\t\022\020\n\010latitude\030\005 \001(\001\022\021\n\tlongitude\030\006 \001(\001\"" +
      "C\n\rAlertResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007mes" +
      "sage\030\002 \001(\t\022\020\n\010alert_id\030\003 \001(\t\"b\n\025Historic" +
      "alDataRequest\022\023\n\013location_id\030\001 \001(\t\022\022\n\nst" +
      "art_time\030\002 \001(\t\022\020\n\010end_time\030\003 \001(\t\022\016\n\006metr" +
      "ic\030\004 \001(\t\"j\n\026HistoricalDataResponse\022\023\n\013lo" +
      "cation_id\030\001 \001(\t\022\016\n\006metric\030\002 \001(\t\022+\n\013data_" +
      "points\030\003 \003(\0132\026.environment.DataPoint\"-\n\t" +
      "DataPoint\022\021\n\ttimestamp\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\001\"D\n\032EnvironmentalUpdateRequest\022\023\n\013loc" +
      "ation_id\030\001 \001(\t\022\021\n\tsubscribe\030\002 \001(\010\"\276\001\n\023En" +
      "vironmentalUpdate\022\023\n\013location_id\030\001 \001(\t\022\023" +
      "\n\013temperature\030\002 \001(\001\022\020\n\010humidity\030\003 \001(\001\022\031\n" +
      "\021air_quality_index\030\004 \001(\001\022\023\n\013noise_level\030" +
      "\005 \001(\001\022\021\n\tco2_level\030\006 \001(\001\022\021\n\ttimestamp\030\007 " +
      "\001(\t\022\025\n\ractive_alerts\030\010 \003(\t2\237\003\n\022Environme" +
      "ntService\022g\n\024GetEnvironmentalData\022%.envi" +
      "ronment.EnvironmentalDataRequest\032&.envir" +
      "onment.EnvironmentalDataResponse\"\000\022S\n\025Re" +
      "portAirQualityAlert\022\034.environment.AirQua" +
      "lityAlert\032\032.environment.AlertResponse\"\000\022" +
      "^\n\021GetHistoricalData\022\".environment.Histo" +
      "ricalDataRequest\032#.environment.Historica" +
      "lDataResponse\"\000\022k\n\032StreamEnvironmentalUp" +
      "dates\022\'.environment.EnvironmentalUpdateR" +
      "equest\032 .environment.EnvironmentalUpdate" +
      "\"\0000\001B<\n\037com.londonsmartcity.environmentB" +
      "\027EnvironmentServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_environment_EnvironmentalDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_environment_EnvironmentalDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_EnvironmentalDataRequest_descriptor,
        new java.lang.String[] { "LocationId", "Latitude", "Longitude", });
    internal_static_environment_EnvironmentalDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_environment_EnvironmentalDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_EnvironmentalDataResponse_descriptor,
        new java.lang.String[] { "LocationId", "Temperature", "Humidity", "AirQualityIndex", "NoiseLevel", "Co2Level", "Timestamp", });
    internal_static_environment_AirQualityAlert_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_environment_AirQualityAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_AirQualityAlert_descriptor,
        new java.lang.String[] { "LocationId", "AlertType", "Severity", "Description", "Latitude", "Longitude", });
    internal_static_environment_AlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_environment_AlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_AlertResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "AlertId", });
    internal_static_environment_HistoricalDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_environment_HistoricalDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_HistoricalDataRequest_descriptor,
        new java.lang.String[] { "LocationId", "StartTime", "EndTime", "Metric", });
    internal_static_environment_HistoricalDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_environment_HistoricalDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_HistoricalDataResponse_descriptor,
        new java.lang.String[] { "LocationId", "Metric", "DataPoints", });
    internal_static_environment_DataPoint_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_environment_DataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_DataPoint_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
    internal_static_environment_EnvironmentalUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_environment_EnvironmentalUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_EnvironmentalUpdateRequest_descriptor,
        new java.lang.String[] { "LocationId", "Subscribe", });
    internal_static_environment_EnvironmentalUpdate_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_environment_EnvironmentalUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environment_EnvironmentalUpdate_descriptor,
        new java.lang.String[] { "LocationId", "Temperature", "Humidity", "AirQualityIndex", "NoiseLevel", "Co2Level", "Timestamp", "ActiveAlerts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
