// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_discovery.proto

package com.londonsmartcity.discovery;

public interface RegistrationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:discovery.RegistrationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string registration_id = 3;</code>
   * @return The registrationId.
   */
  java.lang.String getRegistrationId();
  /**
   * <code>string registration_id = 3;</code>
   * @return The bytes for registrationId.
   */
  com.google.protobuf.ByteString
      getRegistrationIdBytes();
}
