// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_discovery.proto

package com.londonsmartcity.discovery;

public interface ServiceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:discovery.ServiceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_id = 1;</code>
   * @return The serviceId.
   */
  java.lang.String getServiceId();
  /**
   * <code>string service_id = 1;</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();

  /**
   * <code>string service_type = 2;</code>
   * @return The serviceType.
   */
  java.lang.String getServiceType();
  /**
   * <code>string service_type = 2;</code>
   * @return The bytes for serviceType.
   */
  com.google.protobuf.ByteString
      getServiceTypeBytes();

  /**
   * <code>string service_name = 3;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 3;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string host = 4;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <code>string host = 4;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 5;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  int getMetadataCount();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */

  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */

  java.lang.String getMetadataOrThrow(
      java.lang.String key);

  /**
   * <code>string last_heartbeat = 7;</code>
   * @return The lastHeartbeat.
   */
  java.lang.String getLastHeartbeat();
  /**
   * <code>string last_heartbeat = 7;</code>
   * @return The bytes for lastHeartbeat.
   */
  com.google.protobuf.ByteString
      getLastHeartbeatBytes();
}
