// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_discovery.proto

package com.londonsmartcity.discovery;

public final class ServiceDiscoveryProto {
  private ServiceDiscoveryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ServiceRegistration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ServiceRegistration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ServiceRegistration_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ServiceRegistration_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_RegistrationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_RegistrationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ServiceDiscoveryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ServiceDiscoveryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ServiceDiscoveryRequest_FiltersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ServiceDiscoveryRequest_FiltersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ServiceDiscoveryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ServiceDiscoveryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ServiceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ServiceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ServiceInfo_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ServiceInfo_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_UnregisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_UnregisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_UnregisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_UnregisterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027service_discovery.proto\022\tdiscovery\"\342\001\n" +
      "\023ServiceRegistration\022\022\n\nservice_id\030\001 \001(\t" +
      "\022\024\n\014service_type\030\002 \001(\t\022\024\n\014service_name\030\003" +
      " \001(\t\022\014\n\004host\030\004 \001(\t\022\014\n\004port\030\005 \001(\005\022>\n\010meta" +
      "data\030\006 \003(\0132,.discovery.ServiceRegistrati" +
      "on.MetadataEntry\032/\n\rMetadataEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"Q\n\024Registratio" +
      "nResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 " +
      "\001(\t\022\027\n\017registration_id\030\003 \001(\t\"\241\001\n\027Service" +
      "DiscoveryRequest\022\024\n\014service_type\030\001 \001(\t\022@" +
      "\n\007filters\030\002 \003(\0132/.discovery.ServiceDisco" +
      "veryRequest.FiltersEntry\032.\n\014FiltersEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"D\n\030Serv" +
      "iceDiscoveryResponse\022(\n\010services\030\001 \003(\0132\026" +
      ".discovery.ServiceInfo\"\352\001\n\013ServiceInfo\022\022" +
      "\n\nservice_id\030\001 \001(\t\022\024\n\014service_type\030\002 \001(\t" +
      "\022\024\n\014service_name\030\003 \001(\t\022\014\n\004host\030\004 \001(\t\022\014\n\004" +
      "port\030\005 \001(\005\0226\n\010metadata\030\006 \003(\0132$.discovery" +
      ".ServiceInfo.MetadataEntry\022\026\n\016last_heart" +
      "beat\030\007 \001(\t\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\"?\n\020HeartbeatRequest\022" +
      "\022\n\nservice_id\030\001 \001(\t\022\027\n\017registration_id\030\002" +
      " \001(\t\"5\n\021HeartbeatResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\017\n\007message\030\002 \001(\t\"@\n\021UnregisterRequest" +
      "\022\022\n\nservice_id\030\001 \001(\t\022\027\n\017registration_id\030" +
      "\002 \001(\t\"6\n\022UnregisterResponse\022\017\n\007success\030\001" +
      " \001(\010\022\017\n\007message\030\002 \001(\t2\345\002\n\020ServiceDiscove" +
      "ry\022T\n\017RegisterService\022\036.discovery.Servic" +
      "eRegistration\032\037.discovery.RegistrationRe" +
      "sponse\"\000\022]\n\020DiscoverServices\022\".discovery" +
      ".ServiceDiscoveryRequest\032#.discovery.Ser" +
      "viceDiscoveryResponse\"\000\022H\n\tHeartbeat\022\033.d" +
      "iscovery.HeartbeatRequest\032\034.discovery.He" +
      "artbeatResponse\"\000\022R\n\021UnregisterService\022\034" +
      ".discovery.UnregisterRequest\032\035.discovery" +
      ".UnregisterResponse\"\000B8\n\035com.londonsmart" +
      "city.discoveryB\025ServiceDiscoveryProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_discovery_ServiceRegistration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_discovery_ServiceRegistration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ServiceRegistration_descriptor,
        new java.lang.String[] { "ServiceId", "ServiceType", "ServiceName", "Host", "Port", "Metadata", });
    internal_static_discovery_ServiceRegistration_MetadataEntry_descriptor =
      internal_static_discovery_ServiceRegistration_descriptor.getNestedTypes().get(0);
    internal_static_discovery_ServiceRegistration_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ServiceRegistration_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_discovery_RegistrationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_discovery_RegistrationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_RegistrationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "RegistrationId", });
    internal_static_discovery_ServiceDiscoveryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_discovery_ServiceDiscoveryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ServiceDiscoveryRequest_descriptor,
        new java.lang.String[] { "ServiceType", "Filters", });
    internal_static_discovery_ServiceDiscoveryRequest_FiltersEntry_descriptor =
      internal_static_discovery_ServiceDiscoveryRequest_descriptor.getNestedTypes().get(0);
    internal_static_discovery_ServiceDiscoveryRequest_FiltersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ServiceDiscoveryRequest_FiltersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_discovery_ServiceDiscoveryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_discovery_ServiceDiscoveryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ServiceDiscoveryResponse_descriptor,
        new java.lang.String[] { "Services", });
    internal_static_discovery_ServiceInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_discovery_ServiceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ServiceInfo_descriptor,
        new java.lang.String[] { "ServiceId", "ServiceType", "ServiceName", "Host", "Port", "Metadata", "LastHeartbeat", });
    internal_static_discovery_ServiceInfo_MetadataEntry_descriptor =
      internal_static_discovery_ServiceInfo_descriptor.getNestedTypes().get(0);
    internal_static_discovery_ServiceInfo_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ServiceInfo_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_discovery_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_discovery_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_HeartbeatRequest_descriptor,
        new java.lang.String[] { "ServiceId", "RegistrationId", });
    internal_static_discovery_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_discovery_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_discovery_UnregisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_discovery_UnregisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_UnregisterRequest_descriptor,
        new java.lang.String[] { "ServiceId", "RegistrationId", });
    internal_static_discovery_UnregisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_discovery_UnregisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_UnregisterResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
