// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_discovery.proto

package com.londonsmartcity.discovery;

public interface ServiceDiscoveryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:discovery.ServiceDiscoveryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .discovery.ServiceInfo services = 1;</code>
   */
  java.util.List<com.londonsmartcity.discovery.ServiceInfo> 
      getServicesList();
  /**
   * <code>repeated .discovery.ServiceInfo services = 1;</code>
   */
  com.londonsmartcity.discovery.ServiceInfo getServices(int index);
  /**
   * <code>repeated .discovery.ServiceInfo services = 1;</code>
   */
  int getServicesCount();
  /**
   * <code>repeated .discovery.ServiceInfo services = 1;</code>
   */
  java.util.List<? extends com.londonsmartcity.discovery.ServiceInfoOrBuilder> 
      getServicesOrBuilderList();
  /**
   * <code>repeated .discovery.ServiceInfo services = 1;</code>
   */
  com.londonsmartcity.discovery.ServiceInfoOrBuilder getServicesOrBuilder(
      int index);
}
