// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_discovery.proto

package com.londonsmartcity.discovery;

/**
 * Protobuf type {@code discovery.ServiceDiscoveryRequest}
 */
public final class ServiceDiscoveryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:discovery.ServiceDiscoveryRequest)
    ServiceDiscoveryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceDiscoveryRequest.newBuilder() to construct.
  private ServiceDiscoveryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceDiscoveryRequest() {
    serviceType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServiceDiscoveryRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceDiscoveryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceType_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              filters_ = com.google.protobuf.MapField.newMapField(
                  FiltersDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            filters__ = input.readMessage(
                FiltersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            filters_.getMutableMap().put(
                filters__.getKey(), filters__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.londonsmartcity.discovery.ServiceDiscoveryProto.internal_static_discovery_ServiceDiscoveryRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetFilters();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.londonsmartcity.discovery.ServiceDiscoveryProto.internal_static_discovery_ServiceDiscoveryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.londonsmartcity.discovery.ServiceDiscoveryRequest.class, com.londonsmartcity.discovery.ServiceDiscoveryRequest.Builder.class);
  }

  public static final int SERVICE_TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object serviceType_;
  /**
   * <code>string service_type = 1;</code>
   * @return The serviceType.
   */
  @java.lang.Override
  public java.lang.String getServiceType() {
    java.lang.Object ref = serviceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceType_ = s;
      return s;
    }
  }
  /**
   * <code>string service_type = 1;</code>
   * @return The bytes for serviceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceTypeBytes() {
    java.lang.Object ref = serviceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILTERS_FIELD_NUMBER = 2;
  private static final class FiltersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.londonsmartcity.discovery.ServiceDiscoveryProto.internal_static_discovery_ServiceDiscoveryRequest_FiltersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> filters_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetFilters() {
    if (filters_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FiltersDefaultEntryHolder.defaultEntry);
    }
    return filters_;
  }

  public int getFiltersCount() {
    return internalGetFilters().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */

  @java.lang.Override
  public boolean containsFilters(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFilters().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFiltersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getFilters() {
    return getFiltersMap();
  }
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getFiltersMap() {
    return internalGetFilters().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getFiltersOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFilters().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getFiltersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFilters().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceType_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFilters(),
        FiltersDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceType_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetFilters().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      filters__ = FiltersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, filters__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.londonsmartcity.discovery.ServiceDiscoveryRequest)) {
      return super.equals(obj);
    }
    com.londonsmartcity.discovery.ServiceDiscoveryRequest other = (com.londonsmartcity.discovery.ServiceDiscoveryRequest) obj;

    if (!getServiceType()
        .equals(other.getServiceType())) return false;
    if (!internalGetFilters().equals(
        other.internalGetFilters())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getServiceType().hashCode();
    if (!internalGetFilters().getMap().isEmpty()) {
      hash = (37 * hash) + FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFilters().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.londonsmartcity.discovery.ServiceDiscoveryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code discovery.ServiceDiscoveryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:discovery.ServiceDiscoveryRequest)
      com.londonsmartcity.discovery.ServiceDiscoveryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.londonsmartcity.discovery.ServiceDiscoveryProto.internal_static_discovery_ServiceDiscoveryRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetFilters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableFilters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.londonsmartcity.discovery.ServiceDiscoveryProto.internal_static_discovery_ServiceDiscoveryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.londonsmartcity.discovery.ServiceDiscoveryRequest.class, com.londonsmartcity.discovery.ServiceDiscoveryRequest.Builder.class);
    }

    // Construct using com.londonsmartcity.discovery.ServiceDiscoveryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serviceType_ = "";

      internalGetMutableFilters().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.londonsmartcity.discovery.ServiceDiscoveryProto.internal_static_discovery_ServiceDiscoveryRequest_descriptor;
    }

    @java.lang.Override
    public com.londonsmartcity.discovery.ServiceDiscoveryRequest getDefaultInstanceForType() {
      return com.londonsmartcity.discovery.ServiceDiscoveryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.londonsmartcity.discovery.ServiceDiscoveryRequest build() {
      com.londonsmartcity.discovery.ServiceDiscoveryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.londonsmartcity.discovery.ServiceDiscoveryRequest buildPartial() {
      com.londonsmartcity.discovery.ServiceDiscoveryRequest result = new com.londonsmartcity.discovery.ServiceDiscoveryRequest(this);
      int from_bitField0_ = bitField0_;
      result.serviceType_ = serviceType_;
      result.filters_ = internalGetFilters();
      result.filters_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.londonsmartcity.discovery.ServiceDiscoveryRequest) {
        return mergeFrom((com.londonsmartcity.discovery.ServiceDiscoveryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.londonsmartcity.discovery.ServiceDiscoveryRequest other) {
      if (other == com.londonsmartcity.discovery.ServiceDiscoveryRequest.getDefaultInstance()) return this;
      if (!other.getServiceType().isEmpty()) {
        serviceType_ = other.serviceType_;
        onChanged();
      }
      internalGetMutableFilters().mergeFrom(
          other.internalGetFilters());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.londonsmartcity.discovery.ServiceDiscoveryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.londonsmartcity.discovery.ServiceDiscoveryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object serviceType_ = "";
    /**
     * <code>string service_type = 1;</code>
     * @return The serviceType.
     */
    public java.lang.String getServiceType() {
      java.lang.Object ref = serviceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_type = 1;</code>
     * @return The bytes for serviceType.
     */
    public com.google.protobuf.ByteString
        getServiceTypeBytes() {
      java.lang.Object ref = serviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_type = 1;</code>
     * @param value The serviceType to set.
     * @return This builder for chaining.
     */
    public Builder setServiceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string service_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceType() {
      
      serviceType_ = getDefaultInstance().getServiceType();
      onChanged();
      return this;
    }
    /**
     * <code>string service_type = 1;</code>
     * @param value The bytes for serviceType to set.
     * @return This builder for chaining.
     */
    public Builder setServiceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> filters_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetFilters() {
      if (filters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FiltersDefaultEntryHolder.defaultEntry);
      }
      return filters_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableFilters() {
      onChanged();;
      if (filters_ == null) {
        filters_ = com.google.protobuf.MapField.newMapField(
            FiltersDefaultEntryHolder.defaultEntry);
      }
      if (!filters_.isMutable()) {
        filters_ = filters_.copy();
      }
      return filters_;
    }

    public int getFiltersCount() {
      return internalGetFilters().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; filters = 2;</code>
     */

    @java.lang.Override
    public boolean containsFilters(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFilters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFiltersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getFilters() {
      return getFiltersMap();
    }
    /**
     * <code>map&lt;string, string&gt; filters = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getFiltersMap() {
      return internalGetFilters().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; filters = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getFiltersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFilters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; filters = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getFiltersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFilters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFilters() {
      internalGetMutableFilters().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; filters = 2;</code>
     */

    public Builder removeFilters(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFilters().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableFilters() {
      return internalGetMutableFilters().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; filters = 2;</code>
     */
    public Builder putFilters(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableFilters().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; filters = 2;</code>
     */

    public Builder putAllFilters(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableFilters().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:discovery.ServiceDiscoveryRequest)
  }

  // @@protoc_insertion_point(class_scope:discovery.ServiceDiscoveryRequest)
  private static final com.londonsmartcity.discovery.ServiceDiscoveryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.londonsmartcity.discovery.ServiceDiscoveryRequest();
  }

  public static com.londonsmartcity.discovery.ServiceDiscoveryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceDiscoveryRequest>
      PARSER = new com.google.protobuf.AbstractParser<ServiceDiscoveryRequest>() {
    @java.lang.Override
    public ServiceDiscoveryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceDiscoveryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceDiscoveryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceDiscoveryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.londonsmartcity.discovery.ServiceDiscoveryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

