// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_discovery.proto

package com.londonsmartcity.discovery;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:discovery.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_id = 1;</code>
   * @return The serviceId.
   */
  java.lang.String getServiceId();
  /**
   * <code>string service_id = 1;</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();

  /**
   * <code>string registration_id = 2;</code>
   * @return The registrationId.
   */
  java.lang.String getRegistrationId();
  /**
   * <code>string registration_id = 2;</code>
   * @return The bytes for registrationId.
   */
  com.google.protobuf.ByteString
      getRegistrationIdBytes();
}
