// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_discovery.proto

package com.londonsmartcity.discovery;

public interface ServiceDiscoveryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:discovery.ServiceDiscoveryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_type = 1;</code>
   * @return The serviceType.
   */
  java.lang.String getServiceType();
  /**
   * <code>string service_type = 1;</code>
   * @return The bytes for serviceType.
   */
  com.google.protobuf.ByteString
      getServiceTypeBytes();

  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */
  int getFiltersCount();
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */
  boolean containsFilters(
      java.lang.String key);
  /**
   * Use {@link #getFiltersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getFilters();
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getFiltersMap();
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */

  /* nullable */
java.lang.String getFiltersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; filters = 2;</code>
   */

  java.lang.String getFiltersOrThrow(
      java.lang.String key);
}
