// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic_service.proto

package com.londonsmartcity.traffic;

public interface SignalTimingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.londonsmartcity.traffic.SignalTimingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <pre>
   * in seconds
   * </pre>
   *
   * <code>int32 green_duration = 2;</code>
   * @return The greenDuration.
   */
  int getGreenDuration();

  /**
   * <pre>
   * in seconds
   * </pre>
   *
   * <code>int32 yellow_duration = 3;</code>
   * @return The yellowDuration.
   */
  int getYellowDuration();

  /**
   * <pre>
   * in seconds
   * </pre>
   *
   * <code>int32 red_duration = 4;</code>
   * @return The redDuration.
   */
  int getRedDuration();
}
