// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic_service.proto

package com.londonsmartcity.traffic;

public final class TrafficServiceProto {
  private TrafficServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_TrafficStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_TrafficStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_TrafficStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_TrafficStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_SignalTimingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_SignalTimingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_SignalTimingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_SignalTimingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_IncidentReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_IncidentReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_IncidentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_IncidentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_TrafficUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_TrafficUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_TrafficUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_TrafficUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025traffic_service.proto\022\007traffic\"P\n\024Traf" +
      "ficStatusRequest\022\023\n\013location_id\030\001 \001(\t\022\020\n" +
      "\010latitude\030\002 \001(\001\022\021\n\tlongitude\030\003 \001(\001\"\207\001\n\025T" +
      "rafficStatusResponse\022\023\n\013location_id\030\001 \001(" +
      "\t\022\030\n\020congestion_level\030\002 \001(\005\022\025\n\raverage_s" +
      "peed\030\003 \001(\005\022\016\n\006status\030\004 \001(\t\022\030\n\020active_inc" +
      "idents\030\005 \003(\t\"u\n\023SignalTimingRequest\022\027\n\017i" +
      "ntersection_id\030\001 \001(\t\022\026\n\016green_duration\030\002" +
      " \001(\005\022\027\n\017yellow_duration\030\003 \001(\005\022\024\n\014red_dur" +
      "ation\030\004 \001(\005\"P\n\024SignalTimingResponse\022\017\n\007s" +
      "uccess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\026\n\016updated" +
      "_timing\030\003 \001(\t\"\203\001\n\016IncidentReport\022\023\n\013inci" +
      "dent_id\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\022\023\n\013descr" +
      "iption\030\003 \001(\t\022\020\n\010severity\030\004 \001(\t\022\020\n\010latitu" +
      "de\030\005 \001(\001\022\021\n\tlongitude\030\006 \001(\001\"I\n\020IncidentR" +
      "esponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(" +
      "\t\022\023\n\013incident_id\030\003 \001(\t\">\n\024TrafficUpdateR" +
      "equest\022\023\n\013location_id\030\001 \001(\t\022\021\n\tsubscribe" +
      "\030\002 \001(\010\"\222\001\n\rTrafficUpdate\022\023\n\013location_id\030" +
      "\001 \001(\t\022\030\n\020congestion_level\030\002 \001(\005\022\025\n\ravera" +
      "ge_speed\030\003 \001(\005\022\016\n\006status\030\004 \001(\t\022\030\n\020active" +
      "_incidents\030\005 \003(\t\022\021\n\ttimestamp\030\006 \001(\t2\325\002\n\016" +
      "TrafficService\022S\n\020GetTrafficStatus\022\035.tra" +
      "ffic.TrafficStatusRequest\032\036.traffic.Traf" +
      "ficStatusResponse\"\000\022S\n\022UpdateSignalTimin" +
      "g\022\034.traffic.SignalTimingRequest\032\035.traffi" +
      "c.SignalTimingResponse\"\000\022F\n\016ReportIncide" +
      "nt\022\027.traffic.IncidentReport\032\031.traffic.In" +
      "cidentResponse\"\000\022Q\n\024StreamTrafficUpdates" +
      "\022\035.traffic.TrafficUpdateRequest\032\026.traffi" +
      "c.TrafficUpdate\"\0000\001B4\n\033com.londonsmartci" +
      "ty.trafficB\023TrafficServiceProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_traffic_TrafficStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_traffic_TrafficStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_TrafficStatusRequest_descriptor,
        new java.lang.String[] { "LocationId", "Latitude", "Longitude", });
    internal_static_traffic_TrafficStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_traffic_TrafficStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_TrafficStatusResponse_descriptor,
        new java.lang.String[] { "LocationId", "CongestionLevel", "AverageSpeed", "Status", "ActiveIncidents", });
    internal_static_traffic_SignalTimingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_traffic_SignalTimingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_SignalTimingRequest_descriptor,
        new java.lang.String[] { "IntersectionId", "GreenDuration", "YellowDuration", "RedDuration", });
    internal_static_traffic_SignalTimingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_traffic_SignalTimingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_SignalTimingResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "UpdatedTiming", });
    internal_static_traffic_IncidentReport_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_traffic_IncidentReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_IncidentReport_descriptor,
        new java.lang.String[] { "IncidentId", "Location", "Description", "Severity", "Latitude", "Longitude", });
    internal_static_traffic_IncidentResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_traffic_IncidentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_IncidentResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "IncidentId", });
    internal_static_traffic_TrafficUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_traffic_TrafficUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_TrafficUpdateRequest_descriptor,
        new java.lang.String[] { "LocationId", "Subscribe", });
    internal_static_traffic_TrafficUpdate_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_traffic_TrafficUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_TrafficUpdate_descriptor,
        new java.lang.String[] { "LocationId", "CongestionLevel", "AverageSpeed", "Status", "ActiveIncidents", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
