// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_service.proto

package com.londonsmartcity.transport;

public interface ServiceStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.londonsmartcity.transport.ServiceStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string line_id = 1;</code>
   * @return The lineId.
   */
  java.lang.String getLineId();
  /**
   * <code>string line_id = 1;</code>
   * @return The bytes for lineId.
   */
  com.google.protobuf.ByteString
      getLineIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.londonsmartcity.transport.LineStatus line_status = 4;</code>
   * @return Whether the lineStatus field is set.
   */
  boolean hasLineStatus();
  /**
   * <code>.com.londonsmartcity.transport.LineStatus line_status = 4;</code>
   * @return The lineStatus.
   */
  com.londonsmartcity.transport.LineStatus getLineStatus();
  /**
   * <code>.com.londonsmartcity.transport.LineStatus line_status = 4;</code>
   */
  com.londonsmartcity.transport.LineStatusOrBuilder getLineStatusOrBuilder();
}
