// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_service.proto

package com.londonsmartcity.transport;

public final class TransportServiceProto {
  private TransportServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_ArrivalInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_ArrivalInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_ArrivalInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_ArrivalInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_ArrivalInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_ArrivalInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_ServiceStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_ServiceStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_ServiceStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_ServiceStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_LineStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_LineStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_DisruptionReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_DisruptionReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_DisruptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_DisruptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_VehicleLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_VehicleLocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transport_VehicleLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transport_VehicleLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027transport_service.proto\022\ttransport\"N\n\022" +
      "ArrivalInfoRequest\022\017\n\007stop_id\030\001 \001(\t\022\026\n\016t" +
      "ransport_type\030\002 \001(\t\022\017\n\007line_id\030\003 \001(\t\"y\n\023" +
      "ArrivalInfoResponse\022\017\n\007stop_id\030\001 \001(\t\022\026\n\016" +
      "transport_type\030\002 \001(\t\022\017\n\007line_id\030\003 \001(\t\022(\n" +
      "\010arrivals\030\004 \003(\0132\026.transport.ArrivalInfo\"" +
      "\\\n\013ArrivalInfo\022\022\n\nvehicle_id\030\001 \001(\t\022\023\n\013de" +
      "stination\030\002 \001(\t\022\024\n\014minutes_away\030\003 \001(\005\022\016\n" +
      "\006status\030\004 \001(\t\".\n\024ServiceStatusRequest\022\026\n" +
      "\016transport_type\030\001 \001(\t\"U\n\025ServiceStatusRe" +
      "sponse\022\026\n\016transport_type\030\001 \001(\t\022$\n\005lines\030" +
      "\002 \003(\0132\025.transport.LineStatus\"Q\n\nLineStat" +
      "us\022\017\n\007line_id\030\001 \001(\t\022\021\n\tline_name\030\002 \001(\t\022\016" +
      "\n\006status\030\003 \001(\t\022\017\n\007message\030\004 \001(\t\"x\n\020Disru" +
      "ptionReport\022\017\n\007line_id\030\001 \001(\t\022\020\n\010location" +
      "\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\020\n\010severity\030" +
      "\004 \001(\t\022\032\n\022estimated_duration\030\005 \001(\t\"M\n\022Dis" +
      "ruptionResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007mess" +
      "age\030\002 \001(\t\022\025\n\rdisruption_id\030\003 \001(\t\"=\n\026Vehi" +
      "cleLocationRequest\022\017\n\007line_id\030\001 \001(\t\022\022\n\nv" +
      "ehicle_id\030\002 \001(\t\"\220\001\n\017VehicleLocation\022\022\n\nv" +
      "ehicle_id\030\001 \001(\t\022\017\n\007line_id\030\002 \001(\t\022\020\n\010lati" +
      "tude\030\003 \001(\001\022\021\n\tlongitude\030\004 \001(\001\022\r\n\005speed\030\005" +
      " \001(\005\022\021\n\tdirection\030\006 \001(\t\022\021\n\ttimestamp\030\007 \001" +
      "(\t2\355\002\n\020TransportService\022Q\n\016GetArrivalInf" +
      "o\022\035.transport.ArrivalInfoRequest\032\036.trans" +
      "port.ArrivalInfoResponse\"\000\022W\n\020GetService" +
      "Status\022\037.transport.ServiceStatusRequest\032" +
      " .transport.ServiceStatusResponse\"\000\022P\n\020R" +
      "eportDisruption\022\033.transport.DisruptionRe" +
      "port\032\035.transport.DisruptionResponse\"\000\022[\n" +
      "\026StreamVehicleLocations\022!.transport.Vehi" +
      "cleLocationRequest\032\032.transport.VehicleLo" +
      "cation\"\0000\001B8\n\035com.londonsmartcity.transp" +
      "ortB\025TransportServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transport_ArrivalInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transport_ArrivalInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_ArrivalInfoRequest_descriptor,
        new java.lang.String[] { "StopId", "TransportType", "LineId", });
    internal_static_transport_ArrivalInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transport_ArrivalInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_ArrivalInfoResponse_descriptor,
        new java.lang.String[] { "StopId", "TransportType", "LineId", "Arrivals", });
    internal_static_transport_ArrivalInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transport_ArrivalInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_ArrivalInfo_descriptor,
        new java.lang.String[] { "VehicleId", "Destination", "MinutesAway", "Status", });
    internal_static_transport_ServiceStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transport_ServiceStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_ServiceStatusRequest_descriptor,
        new java.lang.String[] { "TransportType", });
    internal_static_transport_ServiceStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_transport_ServiceStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_ServiceStatusResponse_descriptor,
        new java.lang.String[] { "TransportType", "Lines", });
    internal_static_transport_LineStatus_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_transport_LineStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_LineStatus_descriptor,
        new java.lang.String[] { "LineId", "LineName", "Status", "Message", });
    internal_static_transport_DisruptionReport_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_transport_DisruptionReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_DisruptionReport_descriptor,
        new java.lang.String[] { "LineId", "Location", "Description", "Severity", "EstimatedDuration", });
    internal_static_transport_DisruptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_transport_DisruptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_DisruptionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "DisruptionId", });
    internal_static_transport_VehicleLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_transport_VehicleLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_VehicleLocationRequest_descriptor,
        new java.lang.String[] { "LineId", "VehicleId", });
    internal_static_transport_VehicleLocation_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_transport_VehicleLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transport_VehicleLocation_descriptor,
        new java.lang.String[] { "VehicleId", "LineId", "Latitude", "Longitude", "Speed", "Direction", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
