// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_service.proto

package com.londonsmartcity.transport;

public final class TransportServiceProto {
  private TransportServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_ArrivalInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_ArrivalInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_ArrivalInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_ArrivalInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_ArrivalInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_ArrivalInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_ServiceStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_ServiceStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_ServiceStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_ServiceStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_LineStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_LineStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_DisruptionReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_DisruptionReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_DisruptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_DisruptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_VehicleLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_VehicleLocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_londonsmartcity_transport_VehicleLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_londonsmartcity_transport_VehicleLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027transport_service.proto\022\035com.londonsma" +
      "rtcity.transport\"6\n\022ArrivalInfoRequest\022\017" +
      "\n\007stop_id\030\001 \001(\t\022\017\n\007line_id\030\002 \001(\t\"u\n\023Arri" +
      "valInfoResponse\022\017\n\007stop_id\030\001 \001(\t\022\017\n\007line" +
      "_id\030\002 \001(\t\022<\n\010arrivals\030\003 \003(\0132*.com.london" +
      "smartcity.transport.ArrivalInfo\"P\n\013Arriv" +
      "alInfo\022\022\n\nvehicle_id\030\001 \001(\t\022\035\n\025minutes_un" +
      "til_arrival\030\002 \001(\005\022\016\n\006status\030\003 \001(\t\"?\n\024Ser" +
      "viceStatusRequest\022\017\n\007line_id\030\001 \001(\t\022\026\n\016tr" +
      "ansport_type\030\002 \001(\t\"\211\001\n\025ServiceStatusResp" +
      "onse\022\017\n\007line_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\017\n" +
      "\007message\030\003 \001(\t\022>\n\013line_status\030\004 \001(\0132).co" +
      "m.londonsmartcity.transport.LineStatus\"X" +
      "\n\nLineStatus\022\017\n\007line_id\030\001 \001(\t\022\016\n\006status\030" +
      "\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\024\n\014last_updat" +
      "ed\030\004 \001(\003\"J\n\020DisruptionReport\022\017\n\007line_id\030" +
      "\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\020\n\010severity\030\003" +
      " \001(\t\"6\n\022DisruptionResponse\022\017\n\007success\030\001 " +
      "\001(\010\022\017\n\007message\030\002 \001(\t\")\n\026VehicleLocationR" +
      "equest\022\017\n\007line_id\030\001 \001(\t\"}\n\017VehicleLocati" +
      "on\022\022\n\nvehicle_id\030\001 \001(\t\022\017\n\007line_id\030\002 \001(\t\022" +
      "\020\n\010latitude\030\003 \001(\001\022\021\n\tlongitude\030\004 \001(\001\022\r\n\005" +
      "speed\030\005 \001(\005\022\021\n\ttimestamp\030\006 \001(\0032\216\004\n\020Trans" +
      "portService\022y\n\016GetArrivalInfo\0221.com.lond" +
      "onsmartcity.transport.ArrivalInfoRequest" +
      "\0322.com.londonsmartcity.transport.Arrival" +
      "InfoResponse\"\000\022\177\n\020GetServiceStatus\0223.com" +
      ".londonsmartcity.transport.ServiceStatus" +
      "Request\0324.com.londonsmartcity.transport." +
      "ServiceStatusResponse\"\000\022x\n\020ReportDisrupt" +
      "ion\022/.com.londonsmartcity.transport.Disr" +
      "uptionReport\0321.com.londonsmartcity.trans" +
      "port.DisruptionResponse\"\000\022\203\001\n\026StreamVehi" +
      "cleLocations\0225.com.londonsmartcity.trans" +
      "port.VehicleLocationRequest\032..com.london" +
      "smartcity.transport.VehicleLocation\"\0000\001B" +
      "8\n\035com.londonsmartcity.transportB\025Transp" +
      "ortServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_londonsmartcity_transport_ArrivalInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_londonsmartcity_transport_ArrivalInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_ArrivalInfoRequest_descriptor,
        new java.lang.String[] { "StopId", "LineId", });
    internal_static_com_londonsmartcity_transport_ArrivalInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_londonsmartcity_transport_ArrivalInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_ArrivalInfoResponse_descriptor,
        new java.lang.String[] { "StopId", "LineId", "Arrivals", });
    internal_static_com_londonsmartcity_transport_ArrivalInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_londonsmartcity_transport_ArrivalInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_ArrivalInfo_descriptor,
        new java.lang.String[] { "VehicleId", "MinutesUntilArrival", "Status", });
    internal_static_com_londonsmartcity_transport_ServiceStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_londonsmartcity_transport_ServiceStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_ServiceStatusRequest_descriptor,
        new java.lang.String[] { "LineId", "TransportType", });
    internal_static_com_londonsmartcity_transport_ServiceStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_londonsmartcity_transport_ServiceStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_ServiceStatusResponse_descriptor,
        new java.lang.String[] { "LineId", "Status", "Message", "LineStatus", });
    internal_static_com_londonsmartcity_transport_LineStatus_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_londonsmartcity_transport_LineStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_LineStatus_descriptor,
        new java.lang.String[] { "LineId", "Status", "Description", "LastUpdated", });
    internal_static_com_londonsmartcity_transport_DisruptionReport_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_londonsmartcity_transport_DisruptionReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_DisruptionReport_descriptor,
        new java.lang.String[] { "LineId", "Description", "Severity", });
    internal_static_com_londonsmartcity_transport_DisruptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_londonsmartcity_transport_DisruptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_DisruptionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_com_londonsmartcity_transport_VehicleLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_londonsmartcity_transport_VehicleLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_VehicleLocationRequest_descriptor,
        new java.lang.String[] { "LineId", });
    internal_static_com_londonsmartcity_transport_VehicleLocation_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_londonsmartcity_transport_VehicleLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_londonsmartcity_transport_VehicleLocation_descriptor,
        new java.lang.String[] { "VehicleId", "LineId", "Latitude", "Longitude", "Speed", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
